FROM python:3.7

RUN apt-get update && apt-get install -y netcat

RUN mkdir -p /usr/local/heuleum
WORKDIR /usr/local/heuleum

COPY Pipfile Pipfile.lock Makefile .coveragerc /usr/local/heuleum/
COPY tools/docker/.env.local-heuleum /usr/local/heuleum/.env

RUN pip install pipenv

RUN pipenv sync --dev --python 3.7
